name: CS

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Do NOT cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  yamllint:
    name: 'Lint Yaml'
    uses: PHPCSStandards/.github/.github/workflows/reusable-yamllint.yml@main
    with:
      strict: true

  markdownlint:
    name: 'Lint Markdown'
    uses: PHPCSStandards/.github/.github/workflows/reusable-markdownlint.yml@main

  linkcheck:
    name: "Check links"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Restore lychee cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2.6.1
        with:
          # Sidebar file exclusion is needed to work-around an upstream bug.
          # Should be removed once bug https://github.com/lycheeverse/lychee/issues/1788 has been fixed.
          args: --cache --max-cache-age 1w --verbose "./**/*.md" --exclude-path ./wiki/_Sidebar.md
          format: markdown
          token: ${{ secrets.GITHUB_TOKEN }}
          fail: true

  spellcheck:
    name: Spellcheck
    # Config file: .cspell.yml

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@dcd03dc3e8a59ec2e360d0c62db517baa0b4bb6d # v7.2.0
        with:
          # Define glob patterns to filter the files to be checked. Use a new line between patterns to define multiple patterns.
          files: '**/*.md'
          root: '.'
          suggestions: true
          # Notification level for annotations. Allowed values are: warning, error, none
          inline: warning
          treat_flagged_words_as_errors: true
          # Determines if the action should be failed if any spelling issues are found.
          strict: true
          # Limit the files checked to the ones in the pull request or push.
          incremental_files_only: false

  shellcheck:
    name: 'ShellCheck'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up problem matcher
        uses: lumaxis/shellcheck-problem-matchers@b02a1715a00c729b20eed3ebb7edf56fa9a433ba # v2.1.0
        with:
          format: gcc

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          format: gcc
